twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        liqpay: '@App\Service\LiqPayService'
        formhelpsservice: '@App\Service\HelpTextService'