# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'ru'
    avatar_directory: '%kernel.project_dir%/public/sklad-express/uploads/avatars'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Admin,Resources}'

    app.admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Admin, label: Users }

    app.admin.orders:
        class: App\Admin\OrdersAdmin
        arguments: [~, App\Entity\Order, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Admin, label: Orders }


    app.admin.orderstatus:
        class: App\Admin\OrderStatusAdmin
        arguments: [~, App\Entity\OrderStatus, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Settings, label: OrderStatus }

    admin.order_type:
        class: App\Admin\OrderTypeAdmin
        arguments: [~, App\Entity\OrderType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Settings, label: OrderType }
        public: true

    admin.price_weight_econom:
        class: App\Admin\PriceWeightEconomAdmin
        arguments: [~, App\Entity\PriceWeightEconom, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Price, label: PriceWeightEconom }
        public: true

    admin.price_weight_econom_vip:
        class: App\Admin\PriceWeightEconomVipAdmin
        arguments: [~, App\Entity\PriceWeightEconomVip, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Price, label: PriceWeightEconomVip }
        public: true

    admin.price_weight_ekspresss:
        class: App\Admin\PriceWeightEkspressAdmin
        arguments: [~, App\Entity\PriceWeightEkspress, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Price, label: PriceWeightEkspress }
        public: true
    admin.vip_price_weight_ekspresst:
        class: App\Admin\VipPriceWeightEkspressAdmin
        arguments: [~, App\Entity\VipPriceWeightEkspress, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Price, label: VipPriceWeightEkspress }
        public: true

    app.admin.deliveryprice:
            class: App\Admin\DeliveryPriceAdmin
            arguments: [~, App\Entity\DeliveryPrice, ~]
            tags:
            - { name: sonata.admin, manager_type: orm, group: Settings, label: DeliveryPrice }

    app.admin.addresses:
        class: App\Admin\AddressesAdmin
        arguments: [~, App\Entity\Address, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Addresses }

    app.admin.payments:
        class: App\Admin\PaymentsAdmin
        arguments: [~, App\Entity\TransactionLiqPay, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Payments }

    app.admin.invoices:
        class: App\Admin\InvoicesAdmin
        arguments: [~, App\Entity\Invoices,App\Controller\InvoicesAdminController]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Admin, label: Invoices}

    email_service:
        class: App\Service\SendMailService
        calls:
            - [setMailer, ["@mailer"]]
            - [setTemplateEngine, ["@templating"]]

    admin.test:
        class: App\Admin\OrderPraidAdmin
        arguments: [~, App\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: OrdersPraid }
        public: true
